/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-inspector
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_INSPECTOR_API_H
#define INCLUDED_INSPECTOR_API_H

#include <gnuradio/attributes.h>
#ifndef __GR_VLA
#ifdef _MSC_VER
#define __GR_VLA(TYPE, buf, size) TYPE* buf = (TYPE*)alloca(sizeof(TYPE) * (size))
#else
#define __GR_VLA(TYPE, buf, size) TYPE buf[size]
#endif
#endif

#ifdef gnuradio_inspector_EXPORTS
#define INSPECTOR_API __GR_ATTR_EXPORT
#else
#define INSPECTOR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_INSPECTOR_API_H */
